# -*- coding: utf-8 -*-
"""natchuu nm projectipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gZFva4fBY6RRyr_LsMoT1dFtQk-1Oz9w
"""

!pip install gradio pandas

import pandas as pd

# Load the dataset
faq_df = pd.read_csv("faq_data.csv")

# Display first few rows
faq_df.head()

# Shape of the dataset
print("Shape:", faq_df.shape)

# Column names
print("Columns:", faq_df.columns.tolist())

# Check for missing values
print("Missing values:\n", faq_df.isnull().sum())

# Check for duplicates
print("Duplicate rows:", faq_df.duplicated().sum())

def chatbot_response(user_input):
    user_input = user_input.lower()
    for _, row in faq_df.iterrows():
        if row['question_keywords'] in user_input:
            return row['response']
    return "Sorry, I couldn't understand that. Please type 'help'."

import gradio as gr

# Gradio chatbot interface
gr.Interface(
    fn=chatbot_response,
    inputs=gr.Textbox(lines=2, placeholder="Type your customer support question..."),
    outputs="text",
    title="🤖 Intelligent Customer Support Bot",
    description="Ask questions like 'refund', 'order status', 'payment issue', etc."
).launch(share=True)

import pandas as pd
import matplotlib.pyplot as plt

# Load the dataset
faq_df = pd.read_csv("faq_data.csv")

# Count keyword occurrences
keyword_counts = faq_df['question_keywords'].value_counts()

# Plot pie chart
plt.figure(figsize=(6, 6))
plt.pie(keyword_counts, labels=keyword_counts.index, autopct='%1.1f%%', startangle=140, colors=plt.cm.Pastel1.colors)
plt.title("Distribution of FAQs by Keyword")
plt.tight_layout()
plt.show()

import pandas as pd

# Load the dataset
df = pd.read_csv("faq_data.csv")

# Display the first 5 rows
df.head()

# Example preprocessing: Dropping rows with missing values and duplicates
faq_df_cleaned = faq_df.dropna().drop_duplicates()

# Display the first few rows after preprocessing
faq_df_cleaned.head()

import pandas as pd

# Load the dataset again
faq_df = pd.read_csv("faq_data.csv")

# Display the first few rows before preprocessing
faq_df.head()

# Example preprocessing: Dropping rows with missing values and duplicates
faq_df_cleaned = faq_df.dropna().drop_duplicates()

# Display the first few rows after preprocessing
faq_df_cleaned.head()

import pandas as pd
import matplotlib.pyplot as plt

# Load the dataset
faq_df = pd.read_csv("faq_data.csv")

# Count the occurrences of each keyword
keyword_counts = faq_df['question_keywords'].value_counts()

# Plot a pie chart
plt.figure(figsize=(6, 6))
plt.pie(keyword_counts, labels=keyword_counts.index, autopct='%1.1f%%', startangle=140, colors=plt.cm.Pastel1.colors)
plt.title("Distribution of FAQs by Keyword")
plt.tight_layout()
plt.show()